# Generated by Django 2.2.4 on 2019-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=30)),
                ('tue', models.CharField(max_length=30)),
                ('wed', models.CharField(max_length=30)),
                ('thur', models.CharField(max_length=30)),
                ('fri', models.CharField(max_length=30)),
                ('sat', models.CharField(max_length=30)),
                ('sun', models.CharField(max_length=30)),
                ('website', models.TextField()),
                ('map_link', models.TextField()),
            ],
        ),
    ]
